---

- name: add jenkins repo key
  apt_key:
   url: https://pkg.jenkins.io/debian/jenkins.io.key
   state: present
  become: true

- name: add jenkins repo list file into sources.list.d
  apt_repository:
   repo: deb http://pkg.jenkins.io/debian-stable binary/
   state: present
  become: true

- name: install jenkins
  apt:
   name: jenkins
   state: present
   update_cache: yes
  become: true

- include_tasks: settings.yml

- include_tasks: plugins.yml

- include_tasks: build_job.yml
